### ISSUE TITLE
Incorrect URL genered

### ISSUE THREAD

**Issue by astephens43** [facebookresearch/Ego4d#103]
Windows 11, Python 3.8.5

Tried running 
```
python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata --universities="bristol"
python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata
```

In both cases the error I recieved was 
```
...\lib\site-packages\botocore\httpsession.py", line 468, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-consortium-sharing.s3.None.amazonaws.com/public/v1/ego4d.json"
```

I think the 'None' in the URL is incorrect and may come from a default value like ` self.s3_bucket: str = None` in manifest.py (example from line 55).

```
Full Error: 
python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata --universities="bristol"
datasets: ['full_scale', 'annotations']
Download Path: C:\Users\annes\ego4d_data\v1

Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\annes\anaconda3\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\httpsession.py", line 439, in send
    urllib_response = conn.urlopen(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\util\retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000002C7BBF3DC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\annes\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\annes\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\annes\ego4d\Ego4d\ego4d\cli\cli.py", line 220, in <module>
    main(config)
  File "C:\Users\annes\ego4d\Ego4d\ego4d\cli\cli.py", line 63, in main
    metadata_path = download_metadata(
  File "C:\Users\annes\ego4d\Ego4d\ego4d\cli\manifest.py", line 189, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "C:\Users\annes\anaconda3\lib\site-packages\boto3\s3\inject.py", line 359, in object_download_file
    return self.meta.client.download_file(
  File "C:\Users\annes\anaconda3\lib\site-packages\boto3\s3\inject.py", line 190, in download_file
    return transfer.download_file(
  File "C:\Users\annes\anaconda3\lib\site-packages\boto3\s3\transfer.py", line 320, in download_file
    future.result()
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\futures.py", line 103, in result
    return self._coordinator.result()
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\futures.py", line 266, in result
    raise self._exception
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\download.py", line 354, in _submit
    response = client.head_object(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\client.py", line 731, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\client.py", line 751, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 183, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 305, in _needs_retry
    responses = self._event_emitter.emit(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\hooks.py", line 358, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\hooks.py", line 229, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\hooks.py", line 212, in _emit
    response = handler(**kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 194, in __call__
    if self._checker(**checker_kwargs):
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 267, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 294, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 333, in __call__
    checker_response = checker(attempt_number, response,
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 233, in __call__
    return self._check_caught_exception(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 376, in _check_caught_exception
    raise caught_exception
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 249, in _do_get_response
    http_response = self._send(request)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 321, in _send
    return self.http_session.send(request)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\httpsession.py", line 468, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-consortium-sharing.s3.None.amazonaws.com/public/v1/ego4d.json"
PS C:\Users\annes\ego4d\Ego4d> python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata
datasets: ['full_scale', 'annotations']
Download Path: C:\Users\annes\ego4d_data\v1

Downloading Ego4D metadata json..

Traceback (most recent call last):
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\annes\anaconda3\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\httpsession.py", line 439, in send
    urllib_response = conn.urlopen(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\util\retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\annes\anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000002DB9D2EDC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\annes\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\annes\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\annes\ego4d\Ego4d\ego4d\cli\cli.py", line 220, in <module>
    main(config)
  File "C:\Users\annes\ego4d\Ego4d\ego4d\cli\cli.py", line 63, in main
    metadata_path = download_metadata(
  File "C:\Users\annes\ego4d\Ego4d\ego4d\cli\manifest.py", line 189, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "C:\Users\annes\anaconda3\lib\site-packages\boto3\s3\inject.py", line 359, in object_download_file
    return self.meta.client.download_file(
  File "C:\Users\annes\anaconda3\lib\site-packages\boto3\s3\inject.py", line 190, in download_file
    return transfer.download_file(
  File "C:\Users\annes\anaconda3\lib\site-packages\boto3\s3\transfer.py", line 320, in download_file
    future.result()
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\futures.py", line 103, in result
    return self._coordinator.result()
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\futures.py", line 266, in result
    raise self._exception
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\s3transfer\download.py", line 354, in _submit
    response = client.head_object(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\client.py", line 731, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\client.py", line 751, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 183, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 305, in _needs_retry
    responses = self._event_emitter.emit(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\hooks.py", line 358, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\hooks.py", line 229, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\hooks.py", line 212, in _emit
    response = handler(**kwargs)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 194, in __call__
    if self._checker(**checker_kwargs):
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 267, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 294, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 333, in __call__
    checker_response = checker(attempt_number, response,
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 233, in __call__
    return self._check_caught_exception(
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\retryhandler.py", line 376, in _check_caught_exception
    raise caught_exception
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 249, in _do_get_response
    http_response = self._send(request)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\endpoint.py", line 321, in _send
    return self.http_session.send(request)
  File "C:\Users\annes\anaconda3\lib\site-packages\botocore\httpsession.py", line 468, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-consortium-sharing.s3.None.amazonaws.com/public/v1/ego4d.json"
```

**Comment by astephens43** [comment]
The issue was created because the person typed "None" in the aws configure for region and output type rather than pushing enter.  These errors were corrected but the .aws file retained the "None" as an answer - it was included in the URL and reduced it to nonsense.  if you mistakenly type anything in region and output format in the aws configure - you must find the .aws folder and delete the 2 lines in the config file so that  it only contains [default].
