### ISSUE TITLE
Cannot download part of the dataset

### ISSUE THREAD

**Issue by hjl1012** [facebookresearch/Ego4d#118]
Hi,

When I download benchmark EM or FHO using "python -m ego4d.cli.cli --output_directory="I:/Ego4D dataset/ego4d_data" --datasets clips --benchmarks FHO",

I keep getting the error:
"datasets: ['clips']
Download Path: I:\Ego4D dataset\ego4d_data\v1

Ego4D Metadata: I:\Ego4D dataset\ego4d_data\ego4d.json
Checking requested datasets and versions...
Created download directory for version: 'v1' of dataset: 'clips' at:
I:\Ego4D dataset\ego4d_data\v1\clips

Filtering by benchmarks: ['fho']
Retrieving object metadata from S3...
100%|█████████████████████████████████████████████████████████████████████████| 1723/1723 [00:02<00:00, 733.31object/s]
Checking if latest file versions are already downloaded...
  0%|                                                                            | 1/1723 [01:33<44:57:28, 93.99s/file]
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\httpsession.py", line 443, in send
    urllib_response = conn.urlopen(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000001C2D8468E50>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\cli.py", line 220, in <module>
    main(config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\cli.py", line 136, in main
    active_downloads = filter_already_downloaded(
  File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 241, in filter_already_downloaded
    to_download = list(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1129, in __iter__
    for obj in iterable:
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 244, in <lambda>
    lambda x: x.s3_object and not already_downloaded(x) and x.s3_exists,
  File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 193, in already_downloaded
    download.s3_exists = download.exists()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 65, in exists
    self.s3_object.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\boto3\resources\factory.py", line 564, in do_action
    response = action(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 894, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 917, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 116, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 199, in _send_request
    while self._needs_retry(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 351, in _needs_retry
    responses = self._event_emitter.emit(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\utils.py", line 1579, in redirect_from_error
    new_region = self.get_bucket_region(bucket, response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\utils.py", line 1638, in get_bucket_region
    response = self._client.head_bucket(Bucket=bucket)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 894, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 917, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 116, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 199, in _send_request
    while self._needs_retry(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 351, in _needs_retry
    responses = self._event_emitter.emit(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 278, in _do_get_response
    http_response = self._send(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 374, in _send
    return self.http_session.send(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\httpsession.py", line 472, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-unict.s3.eu-central-1.amazonaws.com/"

But I can download benchmark AV successfully.

Has anyone else received the problem? How can I solve this problem?
Thank you so much!

**Comment by ebyrne** [comment]
Are you downloading from China or outside the US?  We've gotten several reports of timeouts from China in particular and are working on better options.  (We were working on proper CDN options, but will likely put up some mirrors in the meantime.  If that's the case here, could you please reach out to info@ego4d-data.org with your info and we'll assist there.)

Possible duplicate: https://github.com/facebookresearch/Ego4d/issues/86

**Comment by hjl1012** [comment]
您好，已收到您的邮件，我会尽快处理。（I have received your e-mail. Thank you!）

**Comment by hjl1012** [comment]
Thank you for your reply! Yes, we download this dataset from China. Our information is presented as follows:


First name: Jianglan; Last name: Huang; ***@***.***; Home Address: Room 202, No.&nbsp;10-1, Lianfeng Road, Jiaocheng District, Ningde, Fujian, China;
City:Ningde; State/Province/County: Fujian; Country: China



Thank you for your help!


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "facebookresearch/Ego4d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月20日(星期一) 凌晨0:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/Ego4d] Cannot download part of the dataset (Issue #118)





 
Are you downloading from China or outside the US?  We've gotten several reports of timeouts from China in particular and are working on better options.  (We were working on proper CDN options, but will likely put up some mirrors in the meantime.  If that's the case here, could you please reach out to ***@***.*** with your info and we'll assist there.)
 
Possible duplicate: #86

**Comment by hjl1012** [comment]
您好，已收到您的邮件，我会尽快处理。（I have received your e-mail. Thank you!）

**Comment by wqtwjt1996** [comment]
@hjl1012 Hi I also wanna download the FHO dataset but got 403 forbidden error:

(ego4d_cli) wqtwjt@dreal2:~/Ego4d$ python -m ego4d.cli.cli --output_directory="./Ego4D" --datasets full_scale annotations --metadata --benchmarks FHO
datasets: ['full_scale', 'annotations']
Download Path: /data/remote/Deep_REAL_Datasets/Ego4D/v1

Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usa/wqtwjt/Ego4d/ego4d/cli/cli.py", line 224, in <module>
    main()
  File "/usa/wqtwjt/Ego4d/ego4d/cli/cli.py", line 220, in main
    main_cfg(config)
  File "/usa/wqtwjt/Ego4d/ego4d/cli/cli.py", line 63, in main_cfg
    metadata_path = download_metadata(
  File "/usa/wqtwjt/Ego4d/ego4d/cli/manifest.py", line 189, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/boto3/s3/inject.py", line 359, in object_download_file
    return self.meta.client.download_file(
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/boto3/s3/transfer.py", line 320, in download_file
    future.result()
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

I saw your comments and it seems like you have no issue with AWS configuration, could you tell me how to set the AWS CLI? You can reach out to me by email: wqtwjt@udel.edu, thanks!!

**Comment by hjl1012** [comment]
您好，已收到您的邮件，我会尽快处理。（I have received your e-mail. Thank you!）

**Comment by devanshk** [comment]
Hi @wqtwjt1996, thanks for your question. Looks like a permissions issue, try this:

1. Make sure you have a valid aws access key. You can get one by signing the license at https://ego4ddataset.com/, and these expire after 14 days.

2. Configure your aws cli to use your access/secret keys. Do this by running `aws configure` in your terminal.

3. Switch to the pip version of the cli with `pip install ego4d`. We'll keep that updated.

4. Re-run your command as
```
ego4d --output_directory="./Ego4D" --datasets full_scale annotations --metadata --benchmarks FHO
```

**Comment by wqtwjt1996** [comment]
Hi I just finished sign the license.

**Comment by wolfworld6** [comment]
> Hi,
> 
> When I download benchmark EM or FHO using "python -m ego4d.cli.cli --output_directory="I:/Ego4D dataset/ego4d_data" --datasets clips --benchmarks FHO",
> 
> I keep getting the error: "datasets: ['clips'] Download Path: I:\Ego4D dataset\ego4d_data\v1
> 
> Ego4D Metadata: I:\Ego4D dataset\ego4d_data\ego4d.json Checking requested datasets and versions... Created download directory for version: 'v1' of dataset: 'clips' at: I:\Ego4D dataset\ego4d_data\v1\clips
> 
> Filtering by benchmarks: ['fho'] Retrieving object metadata from S3... 100%|█████████████████████████████████████████████████████████████████████████| 1723/1723 [00:02<00:00, 733.31object/s] Checking if latest file versions are already downloaded... 0%| | 1/1723 [01:33<44:57:28, 93.99s/file] WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn conn = connection.create_connection( File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection raise err File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection sock.connect(sa) TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\httpsession.py", line 443, in send urllib_response = conn.urlopen( File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen retries = retries.increment( File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 379, in increment raise six.reraise(type(error), error, _stacktrace) File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 735, in reraise raise value File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen httplib_response = self._make_request( File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request self._validate_conn(conn) File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn conn.connect() File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 308, in connect conn = self._new_conn() File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000001C2D8468E50>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\cli.py", line 220, in main(config) File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\cli.py", line 136, in main active_downloads = filter_already_downloaded( File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 241, in filter_already_downloaded to_download = list( File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1129, in **iter** for obj in iterable: File "C:\ProgramData\Anaconda3\lib\concurrent\futures_base.py", line 611, in result_iterator yield fs.pop().result() File "C:\ProgramData\Anaconda3\lib\concurrent\futures_base.py", line 439, in result return self.__get_result() File "C:\ProgramData\Anaconda3\lib\concurrent\futures_base.py", line 388, in __get_result raise self._exception File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 244, in lambda x: x.s3_object and not already_downloaded(x) and x.s3_exists, File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 193, in already_downloaded download.s3_exists = download.exists() File "C:\ProgramData\Anaconda3\lib\site-packages\ego4d\cli\download.py", line 65, in exists self.s3_object.load() File "C:\ProgramData\Anaconda3\lib\site-packages\boto3\resources\factory.py", line 564, in do_action response = action(self, *args, **kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\boto3\resources\action.py", line 88, in **call** response = getattr(parent.meta.client, operation_name)(*args, **params) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 508, in _api_call return self._make_api_call(operation_name, kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 894, in _make_api_call http, parsed_response = self._make_request( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 917, in _make_request return self._endpoint.make_request(operation_model, request_dict) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 116, in make_request return self._send_request(request_dict, operation_model) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 199, in _send_request while self._needs_retry( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 351, in _needs_retry responses = self._event_emitter.emit( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 412, in emit return self._emitter.emit(aliased_event_name, **kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 256, in emit return self._emit(event_name, kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 239, in _emit response = handler(**kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\utils.py", line 1579, in redirect_from_error new_region = self.get_bucket_region(bucket, response) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\utils.py", line 1638, in get_bucket_region response = self._client.head_bucket(Bucket=bucket) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 508, in _api_call return self._make_api_call(operation_name, kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 894, in _make_api_call http, parsed_response = self._make_request( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 917, in _make_request return self._endpoint.make_request(operation_model, request_dict) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 116, in make_request return self._send_request(request_dict, operation_model) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 199, in _send_request while self._needs_retry( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 351, in _needs_retry responses = self._event_emitter.emit( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 412, in emit return self._emitter.emit(aliased_event_name, **kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 256, in emit return self._emit(event_name, kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 239, in _emit response = handler(**kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 207, in **call** if self._checker(**checker_kwargs): File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 284, in **call** should_retry = self._should_retry( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 320, in _should_retry return self._checker(attempt_number, response, caught_exception) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 363, in **call** checker_response = checker( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 247, in **call** return self._check_caught_exception( File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 416, in _check_caught_exception raise caught_exception File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 278, in _do_get_response http_response = self._send(request) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 374, in _send return self.http_session.send(request) File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\httpsession.py", line 472, in send raise EndpointConnectionError(endpoint_url=request.url, error=e) botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-unict.s3.eu-central-1.amazonaws.com/"
> 
> But I can download benchmark AV successfully.
> 
> Has anyone else received the problem? How can I solve this problem? Thank you so much!

I meet the same error, have you solved it ?
