### ISSUE TITLE
Failed to download dataset

### ISSUE THREAD

**Issue by Huhaowen0130** [facebookresearch/Ego4d#123]
Hi, an error occurred when I ran this command: "ego4d --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata".
Could you tell me how to solve it? Thank you!
![image](https://user-images.githubusercontent.com/54608650/180679221-d52a2e06-aaa6-4c31-b980-1d144056db1d.png)

**Comment by gurkirt** [comment]
I have the same issue..... Any help? Seems like organisers are sleeping

**Comment by wqtwjt1996** [comment]
Me too! Any help??!!

**Comment by wqtwjt1996** [comment]
Same issue here I when want to download the FHO benchmark:

(ego4d_cli) wqtwjt@dreal2:~/Ego4d$ python -m ego4d.cli.cli --output_directory="/data/remote/Deep_REAL_Datasets/Ego4D" --datasets full_scale annotations --metadata --benchmarks FHO
datasets: ['full_scale', 'annotations']
Download Path: /data/remote/Deep_REAL_Datasets/Ego4D/v1

Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usa/wqtwjt/Ego4d/ego4d/cli/cli.py", line 224, in <module>
    main()
  File "/usa/wqtwjt/Ego4d/ego4d/cli/cli.py", line 220, in main
    main_cfg(config)
  File "/usa/wqtwjt/Ego4d/ego4d/cli/cli.py", line 63, in main_cfg
    metadata_path = download_metadata(
  File "/usa/wqtwjt/Ego4d/ego4d/cli/manifest.py", line 189, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/boto3/s3/inject.py", line 359, in object_download_file
    return self.meta.client.download_file(
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/boto3/s3/transfer.py", line 320, in download_file
    future.result()
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usa/wqtwjt/anaconda3/envs/ego4d_cli/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by miguelmartin75** [comment]
This seems to be an issue with your certs. Have you configured your aws client? i.e. `aws configure` - otherwise your certs may have expired, please renew them.

**Comment by Huhaowen0130** [comment]
> This seems to be an issue with your certs. Have you configured your aws client? i.e. `aws configure` - otherwise your certs may have expired, please renew them.

Yes, it was because I didn't get the certs from aws. I have downloaded it successfully. Thanks all the same :)

**Comment by Huhaowen0130** [comment]
> I have the same issue..... Any help? Seems like organisers are sleeping

Try to apply here:
https://ego4ddataset.com/

**Comment by Huhaowen0130** [comment]
> Me too! Any help??!!

Try to apply here:
https://ego4ddataset.com/
