### ISSUE TITLE
fail to download annotations_540ss

### ISSUE THREAD

**Issue by idejie** [facebookresearch/Ego4d#154]
Successful command:
```shell
ego4d --output_directory="F:/" --datasets annotations
ego4d --output_directory="G:/" --datasets video_540ss
```

Failed Command:
```shell
ego4d --output_directory="F:/" --datasets annotations_540ss
```

Error:
```
Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['annotations_540ss']
Datasets to download: {'annotations_540ss'}
Download Path: F:\v1
Ego4D Metadata: F:\ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v1' of dataset: 'annotations_540ss' at: F:\v1\annotations_540ss
Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\Scripts\ego4d.exe\__main__.py", line 7, in <module>
  File "C:\Anaconda\lib\site-packages\ego4d\cli\cli.py", line 251, in main
    main_cfg(config)
  File "C:\Anaconda\lib\site-packages\ego4d\cli\cli.py", line 119, in main_cfg
    manifest_path = download_manifest_for_version(
  File "C:\Anaconda\lib\site-packages\ego4d\cli\manifest.py", line 159, in download_manifest_for_version
    _manifest_object(version, dataset, s3).download_file(str(download_path))
  File "C:\Anaconda\lib\site-packages\boto3\s3\inject.py", line 359, in object_download_file
    return self.meta.client.download_file(
  File "C:\Anaconda\lib\site-packages\boto3\s3\inject.py", line 190, in download_file
    return transfer.download_file(
  File "C:\Anaconda\lib\site-packages\boto3\s3\transfer.py", line 320, in download_file
    future.result()
  File "C:\Anaconda\lib\site-packages\s3transfer\futures.py", line 103, in result
    return self._coordinator.result()
  File "C:\Anaconda\lib\site-packages\s3transfer\futures.py", line 266, in result
    raise self._exception
  File "C:\Anaconda\lib\site-packages\s3transfer\tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "C:\Anaconda\lib\site-packages\s3transfer\download.py", line 354, in _submit
    response = client.head_object(
  File "C:\Anaconda\lib\site-packages\botocore\client.py", line 507, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Anaconda\lib\site-packages\botocore\client.py", line 943, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by Linusnie** [comment]
same here with `ego4d --output_directory="~/ego4d_data" --datasets viz`, did you find a solution?

**Comment by Maxlinn** [comment]
it seems annotations_540ss does not exist, i'm sure my connection is ok and spelling is correct, but still get 403.

**Comment by Maxlinn** [comment]
thanks for repsonding but neither `--version v1` or `--version v2` is ok, both are 403.

**Comment by jun297** [comment]
Same issue for me with `--dataset annotations_540ss clips_540ss`

**Comment by Y-Haneji** [comment]
Similar issue for me with `--dataset clips_540ss`.
Are there no 540ss versions?

**Comment by Sanjit-K** [comment]
Has this been solved yet?
