### ISSUE TITLE
Issues downloading ego4d using cli

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/Ego4d#186]
I am running this command `ego4d --output_directory="data" --datasets full-scale --video_uid_file video_uids_nlq_val_v2.txt` in my command line but I am receiving the following error

`Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['full-scale']
ERROR:root:ERROR: video_uids specified for non-video datasets (and will be ignored)
Datasets to download: {'full-scale'}
Download Path: data/v2
Ego4D Metadata: data/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2' of dataset: 'full-scale' at: data/v2/full-scale
Traceback (most recent call last):
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/bin/ego4d", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/ego4d/cli/cli.py", line 119, in main_cfg
    manifest_path = download_manifest_for_version(
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/ego4d/cli/manifest.py", line 159, in download_manifest_for_version
    _manifest_object(version, dataset, s3).download_file(str(download_path))
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/boto3/s3/inject.py", line 359, in object_download_file
    return self.meta.client.download_file(
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/boto3/s3/transfer.py", line 326, in download_file
    future.result()
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/mnt/c/Users/david/Documents/research/fall-2022/Ego4d/ego/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`

The strange thing is that I am able to download the annotations, but just not the videos. My video_uids_nlq_val_v2.txt file contains the clip UIDs that I want to download separated by white spaces. Any one else facing this issue? How do I resolve this? Thank you!

**Comment by miguelmartin75** [comment]
You want `full_scale` not `full-scale`
