### ISSUE TITLE
Build Mephisto Review App Failed

### ISSUE THREAD

**Issue by turtleman99** [facebookresearch/Ego4d#199]
I'm following [README.md](https://github.com/facebookresearch/Ego4d/blob/main/viz/narrations/review/README.md) under `/review` folder to build the review app, and was stuck at 

> 2. Use create-react-app to generate a review app with this template as a base
> 
>     npx create-react-app my-review --template mephisto-review

Specifically, `create-react-app` would install the latest react packages that are incompatible. I followed this [solution](https://stackoverflow.com/a/72685421) to install the `react 17.0.2`. However, 
1. Error was reported by running `yarn build` followed by 
```sh
Internal Error: my-review@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:435:5145)
    at xf.getCandidates (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:391:1264)
    at /home/<username>/anaconda3/envs/Ego/bin/yarn.js:439:7693
    at ff (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:390:11070)
    at ge (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:439:7673)
    at async Promise.allSettled (index 0)
    at async to (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:390:10398)
    at async /home/<username>/anaconda3/envs/Ego/bin/yarn.js:439:8205
    at async ti.startProgressPromise (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:390:47579)
    at async je.resolveEverything (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:439:6233)
```
2. Error was reported by running `yarn install` since many packages cannot be added. For example,
```sh
...
YN0001: │ ReferenceError: whatwg-url@npm:7.1.0: Intl is not defined
    at oRe (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:198:75893)
    at $V.exports (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:198:76293)
    at Ge.truncate (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:412:674)
    at Ge.writeLine (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:409:7013)
    at Ge.reportInfo (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:409:5091)
    at u (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:390:20170)
    at r.reportInfo (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:390:20311)
    at Ge.reportCacheMiss (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:409:2743)
    at onMiss (/home/<username>/anaconda3/envs/Ego/bin/yarn.js:711:2503)
    at /home/<username>/anaconda3/envs/Ego/bin/yarn.js:429:2715
...
```
even with `intl` installed with `npm i intl`.

Any hints or solutions are appreciated. Thanks!

**Comment by ebyrne** [comment]
Do you have a specific use for the local version?  

If not, I'd strongly recommend using the online version to view the dataset: https://visualize.ego4d-data.org/

More details here: https://ego4d-data.org/docs/viz/

**Comment by turtleman99** [comment]
Thanks for the reply, @ebyrne. The online version is very useful.

However, our AWS keys will expire every 14 days. As a result, we need to resign the doc over and over again which is kind of inconvenient.

**Comment by turtleman99** [comment]
Found that I'll receive an updated set of credentials immediately after resubmitting the form. This's awesome! Thank you.

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
