### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by waterljwant** [facebookresearch/Ego4d#218]
Hi, 
Thanks for collecting this awesome dataset!
When I started to download the data with the Access ID and Key granted, I got the error below.
Is this due to an invalid Key or something else? How to solve it?

Traceback (most recent call last):
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jie/Downloads/proj/Ego4d/ego4d/cli/cli.py", line 255, in <module>
    main()
  File "/Users/jie/Downloads/proj/Ego4d/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/Users/jie/Downloads/proj/Ego4d/ego4d/cli/cli.py", line 119, in main_cfg
    manifest_path = download_manifest_for_version(
  File "/Users/jie/Downloads/proj/Ego4d/ego4d/cli/manifest.py", line 160, in download_manifest_for_version
    _manifest_object(version, dataset, s3).download_file(str(download_path))
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/boto3/s3/inject.py", line 359, in object_download_file
    return self.meta.client.download_file(
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/boto3/s3/transfer.py", line 326, in download_file
    future.result()
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jie/miniconda3/envs/ego4d/lib/python3.8/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by Maxlinn** [comment]
i come across the same problem when downloading, i do assure my key and secret are valid.

**Comment by openworld-lab** [comment]
> i come across the same problem when downloading, i do assure my key and secret are valid.
Me too!

**Comment by openworld-lab** [comment]
> > i come across the same problem when downloading, i do assure my key and secret are valid.
> > Me too!
![image](https://github.com/facebookresearch/Ego4d/assets/75013190/fd0deb9d-5ae1-49e1-bf52-f0af953fb4cb)

**Comment by waterljwant** [comment]
I encounter this issue solely while attempting to download the 'vis' dataset. Nevertheless, downloading any other dataset goes smoothly. The 'vis' dataset may be unavailable.

**Comment by olgaiv39** [comment]
Hi, 
I had the same problem trying to download the dataset for audio-visual benchmark 
For the location, now I am based in Krakow, Poland 
the keys and aws configure are right for sure

**Comment by olgaiv39** [comment]
From my point, deleting a comma insert --dataset arg has helped to fix out the download :) 
it might be useful, you might need to check out the syntax of  a download command as well :) 
@waterljwant

**Comment by goodstudent9** [comment]
I solve the problem!
I used to think that I need to create my own access key. Ego4d has a logic that can know who we are from our accesskey
But I am WRONG! We need to use the accesskey that the team provided from the GRANTED Email!
Then everything goes well!
![image](https://github.com/user-attachments/assets/413115c7-226b-4f7d-912a-27c682adae51)

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
