### ISSUE TITLE
Can't specify --uids

### ISSUE THREAD

**Issue by isarandi** [facebookresearch/Ego4d#278]
I'm trying to get one take (got the uid from takes.json), following the docs: `egoexo -o ./ --parts takes --uids 13f01c79-5bfd-42f5-90ce-ee350aa1c3ad`

But I get an exception

```
Traceback (most recent call last):
  File "/home/sarandi/micromamba/envs/egoexo4d/bin/egoexo", line 8, in <module>
    sys.exit(main())
  File "/home/sarandi/micromamba/envs/egoexo4d/lib/python3.10/site-packages/ego4d/egoexo/download/cli.py", line 11, in main
    download_main(args)
  File "/home/sarandi/micromamba/envs/egoexo4d/lib/python3.10/site-packages/ego4d/internal/download/cli.py", line 194, in main
    all_paths.extend([p for p in m.paths if _path_ok(p, args)])
  File "/home/sarandi/micromamba/envs/egoexo4d/lib/python3.10/site-packages/ego4d/internal/download/cli.py", line 194, in <listcomp>
    all_paths.extend([p for p in m.paths if _path_ok(p, args)])
  File "/home/sarandi/micromamba/envs/egoexo4d/lib/python3.10/site-packages/ego4d/internal/download/cli.py", line 31, in _path_ok
    and p.uids is not None
AttributeError: 'PathSpecification' object has no attribute 'uids'
```

The same exception is raised for simply `egoexo -o ./ --uids 13f01c79-5bfd-42f5-90ce-ee350aa1c3ad`

**Comment by tarun005** [comment]
I am facing the same problem. raised an issue here.
https://discuss.ego4d-data.org/t/issues-with-download/424?u=tarunk23

**Comment by tarun005** [comment]
Issue addressed here.

https://discuss.ego4d-data.org/t/issues-with-download/424/2?u=tarunk23

**Comment by miguelmartin75** [comment]
Resolved
