### ISSUE TITLE
Cannot download Ego4D's Unprocessed Data

### ISSUE THREAD

**Issue by Guliisgreat** [facebookresearch/Ego4d#287]
Hi Ego4D team,

To download the Unprocessed video component, I followed the [instruction](https://ego4d-data.org/docs/data/unprocessed_data/) using the command `python -m ego4d.cli.cli --datasets components/videos`, but the error shows `botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`.

I also tried downloading other datasets like canonical video or clips, and they all works. So I was wondering if the unprocessed data is accessible via Ego4D's CLI?

Thanks.

**Comment by juliawilkins** [comment]
Did you set the AWS credentials using the access keys? See https://github.com/facebookresearch/Ego4d/issues/277.

**Comment by juliawilkins** [comment]
Follow-up, @miguelmartin75: I'm finding that when passing many of the university flags in the egoexo CLI, it throws this:

```
Running command: egoexo -o [myoutpath] --parts capture_raw_vrs --splits test -u nus
Filtered 826 -> 20 files
Determining what to download ...
100%|██████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.86it/s]
WARN: failed to get stats for 20 files, will skip. [zero_size=0, exceptions=20]
*** BUCKET FAILURES ***:  {'ego4d-speac'}
Checking current download status ...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/ext3/miniconda3/bin/egoexo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/ext3/miniconda3/lib/python3.11/site-packages/ego4d/egoexo/download/cli.py", line 11, in main
    download_main(args)
  File "/ext3/miniconda3/lib/python3.11/site-packages/ego4d/internal/download/cli.py", line 249, in main
    progress_percent = existing_gib / total_size_gib
                       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```

Any tips? Does this just mean that this university doesn't have the raw capture for this specific split? Wondering if there is any metadata that shows which universities have which splits (and which activities) if possible, to help with selective downloading. Thanks!

**Comment by lixinghe1999** [comment]
Maybe you should set --version v1

Besides, I fail to download unprocessed video with video_uids argument
