### ISSUE TITLE
[EndpointConnectionError],when I download dataset! I have used the VPN.

### ISSUE THREAD

**Issue by Enchantedll** [facebookresearch/Ego4d#296]
ego4d --output_directory="~/ego4d_data" --datasets full_scale annotations --aws_profile_name ego4d
Datasets to download: {'annotations', 'full_scale'}
Download Path: /home/lvwangjing/ego4d_data/v2
Ego4D Metadata: /home/lvwangjing/ego4d_data/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2_1' of dataset: 'annotations' at: /home/lvwangjing/ego4d_data/v2/annotations
Created download directory for version 'v2_1' of dataset: 'full_scale' at: /home/lvwangjing/ego4d_data/v2/full_scale
Retrieving object metadata from S3...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9854/9854 [00:06<00:00, 1508.55object/s]
Checking if latest file versions are already downloaded...
  0%|▎                                                                                                                                                                                 | 16/9854 [00:00<06:50, 23.97file/s]WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
  0%|▌                                                                                                                                                                                 | 31/9854 [00:01<04:08, 39.54file/s]WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
  0%|▊                                                                                                                                                                              | 48/9854 [04:10<14:12:30,  5.22s/file]
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
Traceback (most recent call last):
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/httpsession.py", line 473, in send
    chunked=self._chunked(request.headers),
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f9703701ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lvwangjing/anaconda3/envs/ego4d/bin/ego4d", line 8, in <module>
    sys.exit(main())
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/ego4d/cli/cli.py", line 158, in main_cfg
    skip_s3_checks=validated_cfg.skip_s3_checks,
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/ego4d/cli/download.py", line 255, in filter_already_downloaded
    unit="file",
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/ego4d/cli/download.py", line 251, in <lambda>
    lambda x: x.s3_object and not already_downloaded(x) and x.s3_exists,
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/ego4d/cli/download.py", line 199, in already_downloaded
    skip_s3_checks or download.exists()
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/ego4d/cli/download.py", line 68, in exists
    self.s3_object.load()
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/boto3/resources/factory.py", line 565, in do_action
    response = action(self, *args, **kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/client.py", line 990, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 207, in _send_request
    exception,
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 361, in _needs_retry
    request_dict=request_dict,
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/utils.py", line 1805, in redirect_from_error
    new_region = self.get_bucket_region(bucket, response)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/utils.py", line 1875, in get_bucket_region
    response = self._client.head_bucket(Bucket=bucket)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/client.py", line 990, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 207, in _send_request
    exception,
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 361, in _needs_retry
    request_dict=request_dict,
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/retryhandler.py", line 285, in __call__
    attempt_number, response, caught_exception
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/retryhandler.py", line 364, in __call__
    attempt_number, response, caught_exception
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/retryhandler.py", line 248, in __call__
    attempt_number, caught_exception
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/lvwangjing/anaconda3/envs/ego4d/lib/python3.7/site-packages/botocore/httpsession.py", line 493, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-unict.s3.eu-central-1.amazonaws.com/"

**Comment by shhuangcoder** [comment]
I have the same problem. Have you solved it

**Comment by shhuangcoder** [comment]
I have the same problem. Have you solved it？

**Comment by Amelia168** [comment]
> 我只是使用VPN，尝试了很多次，最后我成功了。

May I ask how you solved this problem?
