### ISSUE TITLE
Cannot Download Ego4D fut_loc data.

### ISSUE THREAD

**Issue by FreddieRao** [facebookresearch/Ego4d#298]
Hi, I'm not able to download the fut_loc dataset, which returns the following error. I have tested my credential enables me to download other datasets, such as imu. Any clue what's going on here?

(base) [user@vscode1 ego4d_data]$ python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets fut_loc annotations
Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['fut_loc']
Datasets to download: {'annotations', 'fut_loc'}
Download Path: /users/user/ego4d_data/v2
Ego4D Metadata: /users/user/ego4d_data/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2_1' of dataset: 'annotations' at: /users/user/ego4d_data/v2/annotations
Created download directory for version 'v2_1' of dataset: 'fut_loc' at: /users/user/ego4d_data/v2/fut_loc
Traceback (most recent call last):
  File "/oscar/runtime/software/external/miniconda3/23.11.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/oscar/runtime/software/external/miniconda3/23.11.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/users/user/.local/lib/python3.10/site-packages/ego4d/cli/cli.py", line 255, in <module>
    main()
  File "/users/user/.local/lib/python3.10/site-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/users/user/.local/lib/python3.10/site-packages/ego4d/cli/cli.py", line 119, in main_cfg
    manifest_path = download_manifest_for_version(
  File "/users/user/.local/lib/python3.10/site-packages/ego4d/cli/manifest.py", line 159, in download_manifest_for_version
    _manifest_object(version, dataset, s3).download_file(str(download_path))
  File "/users/user/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 361, in object_download_file
    return self.meta.client.download_file(
  File "/users/user/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 192, in download_file
    return transfer.download_file(
  File "/users/user/.local/lib/python3.10/site-packages/boto3/s3/transfer.py", line 405, in download_file
    future.result()
  File "/users/user/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/users/user/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/users/user/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/users/user/.local/lib/python3.10/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/users/user/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/users/user/.local/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by Anirudh257** [comment]
Check https://discuss.ego4d-data.org/t/headobject-operation-forbidden-error-permission-not-granted/347/7?u=anirudh and see if it helps.

**Comment by deepseek-ddkk** [comment]
Add --version v1, it be resolved.

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem still persists.
