### ISSUE TITLE
./run_viz got error Could not find AWS profile 'default'.

### ISSUE THREAD

**Issue by Fisher-Wang** [facebookresearch/Ego4d#348]
when i run `./run_viz`, I got this error
```
Preprocessed file not found, downloading the 'viz' dataset using the Ego4D CLI to /home/xxx/ego4d_data/...
Traceback (most recent call last):
  File "/home/xxx/cod/Ego4d/ego4d/cli/config.py", line 117, in validate_config
    boto3.session.Session(profile_name=cfg.aws_profile_name)
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/boto3/session.py", line 88, in __init__
    self._setup_loader()
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/boto3/session.py", line 129, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/session.py", line 802, in get_component
    return self._components.get_component(name)
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/session.py", line 1140, in get_component
    self._components[name] = factory()
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/session.py", line 199, in <lambda>
    lambda: create_loader(self.get_config_variable('data_path')),
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/session.py", line 323, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/configprovider.py", line 472, in get_config_variable
    return provider.provide()
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/configprovider.py", line 678, in provide
    value = provider.provide()
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/configprovider.py", line 765, in provide
    scoped_config = self._session.get_scoped_config()
  File "/home/xxx/miniforge3/lib/python3.10/site-packages/botocore/session.py", line 422, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/miniforge3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/miniforge3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxx/cod/Ego4d/ego4d/cli/cli.py", line 255, in <module>
    main()
  File "/home/xxx/cod/Ego4d/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/home/xxx/cod/Ego4d/ego4d/cli/cli.py", line 48, in main_cfg
    validated_cfg = validate_config(cfg)
  File "/home/xxx/cod/Ego4d/ego4d/cli/config.py", line 119, in validate_config
    raise RuntimeError(f"Could not find AWS profile '{cfg.aws_profile_name}'.")
RuntimeError: Could not find AWS profile 'default'.
```

when I run `ego4d --datasets viz --output_directory .`, I got the same error
```
Traceback (most recent call last):
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/ego4d/cli/config.py", line 117, in validate_config
    boto3.session.Session(profile_name=cfg.aws_profile_name)
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/boto3/session.py", line 88, in __init__
    self._setup_loader()
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/boto3/session.py", line 129, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/session.py", line 802, in get_component
    return self._components.get_component(name)
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/session.py", line 1140, in get_component
    self._components[name] = factory()
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/session.py", line 199, in <lambda>
    lambda: create_loader(self.get_config_variable('data_path')),
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/session.py", line 323, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/configprovider.py", line 472, in get_config_variable
    return provider.provide()
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/configprovider.py", line 678, in provide
    value = provider.provide()
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/configprovider.py", line 765, in provide
    scoped_config = self._session.get_scoped_config()
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/session.py", line 422, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/.local/bin/ego4d", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/ego4d/cli/cli.py", line 48, in main_cfg
    validated_cfg = validate_config(cfg)
  File "/home/xxx/.local/pipx/venvs/ego4d/lib/python3.10/site-packages/ego4d/cli/config.py", line 119, in validate_config
    raise RuntimeError(f"Could not find AWS profile '{cfg.aws_profile_name}'.")
RuntimeError: Could not find AWS profile 'default'.
```

**Comment by yongliang-wu** [comment]
Hi, have you solved the problem?

**Comment by miguelmartin75** [comment]
Please follow this: https://docs.ego-exo4d-data.org/download/#setup-aws-client - the same steps apply for Ego4d.

**Comment by Fisher-Wang** [comment]
> Please follow this: https://docs.ego-exo4d-data.org/download/#setup-aws-client - the same steps apply for Ego4d.

This one works. Thank you!
