### ISSUE TITLE
Fail to download

### ISSUE THREAD

**Issue by Fisher-Wang** [facebookresearch/Ego4d#354]
When I tried to download the dataset with `ego4d --datasets clips --output_directory .`, I got the error:
```
Datasets to download: {'clips'}
Download Path: v2
Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "/home/xxx/.local/bin/ego4d", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/ego4d/cli/cli.py", line 74, in main_cfg
    metadata_path = download_metadata(
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/ego4d/cli/manifest.py", line 199, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/boto3/s3/inject.py", line 361, in object_download_file
    return self.meta.client.download_file(
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/boto3/s3/inject.py", line 192, in download_file
    return transfer.download_file(
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/boto3/s3/transfer.py", line 406, in download_file
    future.result()
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/xxx/.local/share/pipx/venvs/ego4d/lib/python3.10/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

It seems something wrong with the Amazon bucket.

**Comment by qingxinxia** [comment]
me too, did you addressed this issue?

**Comment by qingxinxia** [comment]
Thank you very much. I could not get my access key & secret key. 

Should I wait for a few days after I sign on Dropbox?

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists. Thanks!
