### ISSUE TITLE
Can't download Ego4D

### ISSUE THREAD

**Issue by Geeksun2018** [facebookresearch/Ego4d#50]
Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "E:\SoftWare\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\SoftWare\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Project\project\Ego4d\ego4d\cli\cli.py", line 216, in <module>
    main(config)
  File "E:\Project\project\Ego4d\ego4d\cli\cli.py", line 63, in main
    metadata_path = download_metadata(
  File "E:\Project\project\Ego4d\ego4d\cli\manifest.py", line 189, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "E:\SoftWare\Anaconda\lib\site-packages\boto3\s3\inject.py", line 319, in object_download_file
    return self.meta.client.download_file(
  File "E:\SoftWare\Anaconda\lib\site-packages\boto3\s3\inject.py", line 173, in download_file
    return transfer.download_file(
  File "E:\SoftWare\Anaconda\lib\site-packages\boto3\s3\transfer.py", line 315, in download_file
    future.result()
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\futures.py", line 103, in result
    return self._coordinator.result()
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\futures.py", line 266, in result
    raise self._exception
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\download.py", line 354, in _submit
    response = client.head_object(
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by ebyrne** [comment]
Have you setup your AWS key via `aws configure`?  Can you please provide the steps and command used? @Geeksun2018

**Comment by iranroman** [comment]
On my end, I was able to download the `annotations`, but when I try to download the `full_scale` or the `clips`, I get `connectionpool` warnings and ultimately a timeout error. 

Is there something specific that I should do to be able to download things other than the annotations?

**Comment by ebyrne** [comment]
Not really.  You're the second person that has reported timeouts.  (Dropped connectionpool warnings unfortunately seem to be pretty common, but shouldn't fail anything.)  I'm assuming you have a decent connection and actual timeouts wouldn't be resonable?  I'll look at adding some options for longer timeouts tomorrow.  For now, could you just retry and see if that doesn't incrementally succeed?  (If you're letting it run and it's not properly accounting for those downloaded files on the next run, please let me know and include the output.)

**Comment by Geeksun2018** [comment]
> Have you setup your AWS key via `aws configure`? Can you please provide the steps and command used? @Geeksun2018

yes, this is the step.
![image](https://user-images.githubusercontent.com/42086593/155046742-3b69911a-c35b-475e-aaef-3c6953fa6c00.png)
I just download the dataset again, and the error is the same like yesterday.But when I set my proxy to global, there is a different error report.

`(base) PS E:\Project\project\Ego4d> python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata  --benchmarks AV
datasets: ['full_scale', 'annotations']
Download Path: C:\Users\99570\ego4d_data\v1

Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\SoftWare\Anaconda\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\SoftWare\Anaconda\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "E:\SoftWare\Anaconda\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\httpsession.py", line 403, in send
    urllib_response = conn.urlopen(
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\util\retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\SoftWare\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\SoftWare\Anaconda\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\SoftWare\Anaconda\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "E:\SoftWare\Anaconda\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProxyError: ('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\SoftWare\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\SoftWare\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Project\project\Ego4d\ego4d\cli\cli.py", line 216, in <module>
    main(config)
  File "E:\Project\project\Ego4d\ego4d\cli\cli.py", line 63, in main
    metadata_path = download_metadata(
  File "E:\Project\project\Ego4d\ego4d\cli\manifest.py", line 189, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "E:\SoftWare\Anaconda\lib\site-packages\boto3\s3\inject.py", line 319, in object_download_file
    return self.meta.client.download_file(
  File "E:\SoftWare\Anaconda\lib\site-packages\boto3\s3\inject.py", line 173, in download_file
    return transfer.download_file(
  File "E:\SoftWare\Anaconda\lib\site-packages\boto3\s3\transfer.py", line 315, in download_file
    future.result()
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\futures.py", line 103, in result
    return self._coordinator.result()
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\futures.py", line 266, in result
    raise self._exception
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "E:\SoftWare\Anaconda\lib\site-packages\s3transfer\download.py", line 354, in _submit
    response = client.head_object(
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\client.py", line 705, in _make_api_call
    http, parsed_response = self._make_request(
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\client.py", line 725, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\endpoint.py", line 106, in make_request
    return self._send_request(request_dict, operation_model)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\endpoint.py", line 182, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\endpoint.py", line 301, in _needs_retry
    responses = self._event_emitter.emit(
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\retryhandler.py", line 192, in __call__
    if self._checker(**checker_kwargs):
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\retryhandler.py", line 265, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\retryhandler.py", line 292, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\retryhandler.py", line 331, in __call__
    checker_response = checker(attempt_number, response,
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\retryhandler.py", line 231, in __call__
    return self._check_caught_exception(
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\retryhandler.py", line 374, in _check_caught_exception
    raise caught_exception
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\endpoint.py", line 248, in _do_get_response
    http_response = self._send(request)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\endpoint.py", line 317, in _send
    return self.http_session.send(request)
  File "E:\SoftWare\Anaconda\lib\site-packages\botocore\httpsession.py", line 434, in send
    raise ProxyConnectionError(proxy_url=mask_proxy_url(proxy_url), error=e)
botocore.exceptions.ProxyConnectionError: Failed to connect to proxy URL: "https://127.0.0.1:3334"`

**Comment by ebyrne** [comment]
Apologies, but that's just a standard proxy issue and I don't have enough info on the first one to help you here.  

If you were able to download the annotations I'm not sure what it could be.  Drop more info here and I'll see if I can help.

**Comment by Geeksun2018** [comment]
> 抱歉，但这只是一个标准的代理问题，我没有足够的信息来帮助你。
> 
> 如果您能够下载注释，我不确定它可能是什么。在此处删除更多信息，我会看看是否可以提供帮助。

thank you!!!
