### ISSUE TITLE
Download issue: botocore.exceptions.ClientError

### ISSUE THREAD

**Issue by WikiChao** [facebookresearch/Ego4d#57]
Hi,

When I try to download the dataset by following the instructions, I have encountered this problem:

botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

Any idea about how to fix this? Thanks in advance!

**Comment by ebyrne** [comment]
Have you setup your AWS key via aws configure? Can you please provide the steps and command used?

https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md

**Comment by ashantanu** [comment]
Getting the same error when trying to download `full-scale` dataset. I have setup my AWS key and have been able to download annotations and slowfast features. Moreover, when providing `video_uids`, I get 
`ERROR:root:ERROR: video_uids specified for non-video datasets (and will be ignored)`

Appreciate the help, thanks!

**Comment by ashantanu** [comment]
I am providing uids with full-scale, below is the command
`python -m ego4d.cli.cli --output_directory="../ego4d_data" --datasets full-scale --video_uids 7bc80e9a-d235-4245-9876-9f414969b6d0 f8c36c51-1cca-4ed3-81db-c190b72d5c49`

Output:
```
Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['full-scale']
datasets: ['full-scale']
ERROR:root:ERROR: video_uids specified for non-video datasets (and will be ignored)
Download Path: ../ego4d_data/v1

Ego4D Metadata: ../ego4d_data/ego4d.json
Checking requested datasets and versions...
Created download directory for version: 'v1' of dataset: 'full-scale' at:
../ego4d_data/v1/full-scale

Traceback (most recent call last):
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shantanuagar_umass_edu/Ego4d/ego4d/cli/cli.py", line 216, in <module>
    main(config)
  File "/home/shantanuagar_umass_edu/Ego4d/ego4d/cli/cli.py", line 101, in main
    manifest_path = download_manifest_for_version(
  File "/home/shantanuagar_umass_edu/Ego4d/ego4d/cli/manifest.py", line 149, in download_manifest_for_version
    _manifest_object(version, dataset, s3).download_file(str(download_path))
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/boto3-1.21.3-py3.9.egg/boto3/s3/inject.py", line 319, in object_download_file
    return self.meta.client.download_file(
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/boto3-1.21.3-py3.9.egg/boto3/s3/inject.py", line 173, in download_file
    return transfer.download_file(
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/boto3-1.21.3-py3.9.egg/boto3/s3/transfer.py", line 315, in download_file
    future.result()
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/s3transfer-0.5.1-py3.9.egg/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/s3transfer-0.5.1-py3.9.egg/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/s3transfer-0.5.1-py3.9.egg/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/s3transfer-0.5.1-py3.9.egg/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/botocore-1.24.3-py3.9.egg/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/shantanuagar_umass_edu/miniconda3/lib/python3.9/site-packages/botocore-1.24.3-py3.9.egg/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by ebyrne** [comment]
Ah, that's the problem.  You specified `full-scale`, not `full_scale`.  See the warning above.  (Will make that more explicit going forward.)

**Comment by WikiChao** [comment]
> Have you setup your AWS key via aws configure? Can you please provide the steps and command used?
> 
> https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md

Yes, this problem has been fixed by updating the configuration! But when I try to download a subset of Ego4d with command "python -m ego4d.cli.cli --output_directory="../ego4d_data" --datasets full_scale annotations --metadata --universities georgiatech", I get the following error:

Checking if latest file versions are already downloaded...
Traceback (most recent call last):
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cxu-serve/p1/chuang65/dataset/Ego4d/ego4d/cli/cli.py", line 220, in <module>
    main(config)
  File "/home/cxu-serve/p1/chuang65/dataset/Ego4d/ego4d/cli/cli.py", line 136, in main
    active_downloads = filter_already_downloaded(
TypeError: filter_already_downloaded() got an unexpected keyword argument 'bypass_check'

Since it's the first time I download the dataset, it should be no problem with "filter_already_downloaded()" function. 

Looking forward to getting some suggestions. Appreciate the help, thanks!

**Comment by ebyrne** [comment]
You using a stale version of the CLI.  (There was a bug introduced brielfy.) Please `git pull`

**Comment by WikiChao** [comment]
That solves my problem, thanks a lot!
