### ISSUE TITLE
Files failed download

### ISSUE THREAD

**Issue by WikiChao** [facebookresearch/Ego4d#63]
Hi,

I was downloading the data from a subset with "python -m ego4d.cli.cli --output_directory="/ego4d_data" --datasets full_scale annotations --metadata --universities bristol ", but got the following errors:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cxu-serve/p1/chuang65/dataset/Ego4d/ego4d/cli/download.py", line 302, in download_video
    obj.download_file(str(file_path), Callback=callback)
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/boto3-1.21.5-py3.8.egg/boto3/s3/inject.py", line 319, in object_download_file
    return self.meta.client.download_file(
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/boto3-1.21.5-py3.8.egg/boto3/s3/inject.py", line 173, in download_file
    return transfer.download_file(
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/boto3-1.21.5-py3.8.egg/boto3/s3/transfer.py", line 315, in download_file
    future.result()
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer-0.5.1-py3.8.egg/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer-0.5.1-py3.8.egg/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer-0.5.1-py3.8.egg/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer-0.5.1-py3.8.egg/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer-0.5.1-py3.8.egg/s3transfer/download.py", line 583, in _main
    for chunk in chunks:
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer-0.5.1-py3.8.egg/s3transfer/download.py", line 728, in __next__
    chunk = self._body.read(self._chunksize)
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/s3transfer-0.5.1-py3.8.egg/s3transfer/utils.py", line 599, in read
    value = self._stream.read(*args, **kwargs)
  File "/home/cxu-serve/u1/chuang65/anaconda3/envs/ego4d/lib/python3.8/site-packages/botocore-1.24.5-py3.8.egg/botocore/response.py", line 100, in read
    raise ResponseStreamingError(error=e)
botocore.exceptions.ResponseStreamingError: An error occurred while reading from response stream: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

Checking file integrity...
ERROR:root:ERROR: 8 files failed download:      d38f271c-53f3-4771-8c17-a5157e723067
        31ea56e6-7a99-4b91-b74b-3b1e6de05e99
        504315c0-17fd-4259-9d2c-fd2b25fdcbea
        ae9cb412-7b93-49ae-bb46-306dc74d5fe3
        a855cacc-0c0f-4ad3-9991-90cbd761637a
        f3a9685f-0238-45a8-b7f5-30660e4d3acf
        fbaa9e09-62c9-460a-b44b-d1db9e5f4039
        05df9f6f-90b8-4ed0-81c7-c0e98a730f6f

WARNING:root:upsert_version: ignoring 0 byte download: d38f271c-53f3-4771-8c17-a5157e723067
WARNING:root:upsert_version: ignoring 0 byte download: 31ea56e6-7a99-4b91-b74b-3b1e6de05e99
WARNING:root:upsert_version: ignoring 0 byte download: 504315c0-17fd-4259-9d2c-fd2b25fdcbea
WARNING:root:upsert_version: ignoring 0 byte download: ae9cb412-7b93-49ae-bb46-306dc74d5fe3
WARNING:root:upsert_version: ignoring 0 byte download: a855cacc-0c0f-4ad3-9991-90cbd761637a
WARNING:root:upsert_version: ignoring 0 byte download: f3a9685f-0238-45a8-b7f5-30660e4d3acf
WARNING:root:upsert_version: ignoring 0 byte download: fbaa9e09-62c9-460a-b44b-d1db9e5f4039
WARNING:root:upsert_version: ignoring 0 byte download: 05df9f6f-90b8-4ed0-81c7-c0e98a730f6f

It seems that I have already downloaded some of the videos successfully. Not sure what's the reason, could you please help me check this? Thanks!

**Comment by ebyrne** [comment]
Please provide the full command and output with help requests and review the CLI README for arguments.
