### ISSUE TITLE
cannot download dataset

### ISSUE THREAD

**Issue by sanketsans** [facebookresearch/Ego4d#80]
Hi, 
I keep getting the error "An error occurred (403) when calling the HeadObject operation: Forbidden" when I run the CLI command to download the dataset. I am already an IAM user with root privileges and added the key & the id for AWS cli. 

Has anyone else received the problem? 
Thanks

**Comment by ebyrne** [comment]
Is this for `full_scale`?  Can you provide the full commands you used to download and configure AWS?  (We've had a few hundred downloads to date without this being reported for the primary datasets.)

**Comment by sanketsans** [comment]
Yes. I tried downloading full_scale and specific benchmark set, but unfortunately, both cases have the same problem. 
I use this command as specified : `
python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata --aws_profile_name ego4d`
where ego4d is my aws_profile_name created with the access Id and key. The error reported above is when I leave the default region as blank but I tried changing that to global then I get a new error : 
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-consortium-sharing.s3.global.amazonaws.com/public/v1/ego4d.json"

I tried making a new AWS profile as well, but even then the same problem persists. I noticed that there were some people who faced a similar issue in the solved issue(s) section. But apparently, there is nothing substantial as to how to resolve this issue.

**Comment by sanketsans** [comment]
Do I need to set up a profile or enable some permissions on AWS for my account ?

**Comment by idejie** [comment]
I also encountered this problem.
Does the data download require certain permissions? Or a specific AWS Access Credential?

```
$python -m ego4d.cli.cli --output_directory="ego4d_data" --datasets full_scale annotations --metadata                                                                                                                                                                                                                                                                                                                                               


datasets: ['full_scale', 'annotations']
Download Path: ego4d_data/v1

Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/idejie/Projects/Ego4d/ego4d/cli/cli.py", line 220, in <module>
    main(config)
  File "/Users/idejie/Projects/Ego4d/ego4d/cli/cli.py", line 66, in main
    s3,
  File "/Users/idejie/Projects/Ego4d/ego4d/cli/manifest.py", line 189, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/boto3/s3/inject.py", line 315, in object_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/boto3/s3/inject.py", line 173, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/s3transfer/download.py", line 343, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/idejie/anaconda3/envs/Tools/lib/python3.7/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by ebyrne** [comment]
@sanketsans Could you share the aws configure command you're using? (And just to confirm, when you tried global you did just `aws configure` without a profile name, then provided the key & secret and left the next 2 prompts blank, and then removed the `--aws_profile_name` argument correct?)

@idejie When you say specific AWS credentials, to confirm you signed the license agreement and received your key 48 hrs later as described here correct? https://ego4d-data.org/docs/start-here/

**Comment by sanketsans** [comment]
@ebyrne yes. I get connection issues when I set the region as global or None. It is now working fine when I set the region as us-west-1. 

@idejie You need to sign the request form and as @ebyrne said it takes about 48 hrs to get the was credentials to download the dataset.

**Comment by idejie** [comment]
Thanks. Before that, I have sent the request. I will retry to download after the key is received.
